# Description: Run the magnitude_squared_coherence.py script for flat trials
python magnitude_squared_coherence.py --file logging_phase_flat_1_0_5_contra_rule2
python magnitude_squared_coherence.py --file logging_phase_flat_2_0_5_contra_rule2
python magnitude_squared_coherence.py --file logging_phase_flat_3_0_5_contra_rule2
python magnitude_squared_coherence.py --file logging_phase_flat_4_0_5_contra_rule2
python magnitude_squared_coherence.py --file logging_phase_flat_5_0_5_contra_rule2
python magnitude_squared_coherence.py --file logging_phase_flat_6_0_5_contra_rule2
python magnitude_squared_coherence.py --file logging_phase_flat_takes2_2_contra_rule2_0
python magnitude_squared_coherence.py --file logging_phase_flat_extra1
python magnitude_squared_coherence.py --file logging_phase_flat_extra4
python magnitude_squared_coherence.py --file logging_phase_flat_extra5
python magnitude_squared_coherence.py --file logging_phase_flat_extra6
python magnitude_squared_coherence.py --file logging_phase_flat_extra7

# terrain
python magnitude_squared_coherence.py --file logging_phase_terrain_1
python magnitude_squared_coherence.py --file logging_phase_terrain_2_0_5_contra_rule2
python magnitude_squared_coherence.py --file logging_phase_terrain_3_0_5_contra_rule2
python magnitude_squared_coherence.py --file logging_phase_terrain_4_0_5_contra_rule2
python magnitude_squared_coherence.py --file logging_phase_terrain_5_0_5_contra_rule2

# Ablation
python magnitude_squared_coherence.py --file logging_phase_flat_ablation_all1
python magnitude_squared_coherence.py --file logging_phase_flat_ablation_all2
python magnitude_squared_coherence.py --file logging_phase_flat_ablation_all3
python magnitude_squared_coherence.py --file logging_phase_flat_ablation_all4

# Amputate L2
python magnitude_squared_coherence.py --file logging_phase_flat_1_middle_amputation_1
python magnitude_squared_coherence.py --file logging_phase_flat_1_middle_amputation_2
python magnitude_squared_coherence.py --file logging_phase_flat_1_middle_amputation_3
python magnitude_squared_coherence.py --file logging_phase_flat_1_middle_amputation_4
python magnitude_squared_coherence.py --file logging_phase_flat_1_middle_amputation_5
python magnitude_squared_coherence.py --file logging_phase_flat_1_middle_amputation_6

# Amputate L3
python magnitude_squared_coherence.py --file logging_phase_flat_left_hind_amputation1
python magnitude_squared_coherence.py --file logging_phase_flat_left_hind_amputation2
python magnitude_squared_coherence.py --file logging_phase_flat_left_hind_amputation3
python magnitude_squared_coherence.py --file logging_phase_flat_left_hind_amputation4
python magnitude_squared_coherence.py --file logging_phase_flat_left_hind_amputation5
python magnitude_squared_coherence.py --file logging_phase_flat_left_hind_amputation6

# Amputate L2R2
python magnitude_squared_coherence.py --file logging_phase_flat_both_middle_amputation1
python magnitude_squared_coherence.py --file logging_phase_flat_both_middle_amputation2
python magnitude_squared_coherence.py --file logging_phase_flat_both_middle_amputation3
python magnitude_squared_coherence.py --file logging_phase_flat_both_middle_amputation4
python magnitude_squared_coherence.py --file logging_phase_flat_both_middle_amputation5
python magnitude_squared_coherence.py --file logging_phase_flat_both_middle_amputation6

# Amputate L3R3
python magnitude_squared_coherence.py --file logging_phase_flat_both_hind_amputation1
python magnitude_squared_coherence.py --file logging_phase_flat_both_hind_amputation2
python magnitude_squared_coherence.py --file logging_phase_flat_both_hind_amputation3
python magnitude_squared_coherence.py --file logging_phase_flat_both_hind_amputation5
python magnitude_squared_coherence.py --file logging_phase_flat_both_hind_amputation6
